In [221]:
# A 1
# B 2
# C 3
# D 4
# E 5
# F 6
# G 7
# H 8
# I 9
# J 10
# K 11
# L 12
# M 13
# N 14
# O 15
# P 16
# Q 17
# R 18
# S 19
# T 20
# U 21
# V 22
# W 23
# X 24
# Y 25
# Z 26

## work simulation

In [223]:
# A 1-2 M
# B 4-6 H
# C 2-4 L
# D 2-4 M
# E 5-9 H
# F 3-5 H
# G 2-4 M
# H 1-2 L

In [224]:
# F 3-5 H
# B 4-6 H
# E 5-9 H
# A 1-2 M
# D 2-4 M
# G 2-4 M
# H 1-2 L
# C 2-4 L

In [226]:
# F > B > E
# A > D = G > C
# A > H

In [ ]:
# ADF > ACF
# ADF > ABD > ACDF > ACDGH

In [ ]:
# FG    5-9   HM    6
# ADF   6-11  MMH   5
# ACF   6-11  MLH   4
# ABD   7-12  MHM   3
# ACDG  7-14  MLMM  2
# ACDGH 8-16  MLMML 1

Are we receiving complaints from customers?

Do any other projects depend on fixing this problem?

How long will it take to solve this problem?

If I help you with this problem, will you help me finish my work today?

How many customers is this affecting?

How does this affect customers?

## Round Robin

In [283]:
class Solution:
    def waitingTimeRobin(self, arrival, run, q):
        # base case
        if not (arrival or run) or len(arrival) != len(run) or q <= 0:
            return 0
        
        wait0 = [x + y for x, y in zip(arrival, run)]
        time = arrival[0]
        qlst = [0] # index
        result = []
        self.helper(arrival, run, q, 0, result, time, qlst, wait0)
        return result[0] / len(arrival)

    def helper(self, arrival, run, q, cumu, result, time, qlst, wait0):
        if qlst:
            runi = qlst.pop(0) # index
            intervel = min(run[runi], q)
            run[runi] -= intervel
            
            i = runi + 1
            while i < len(arrival):
                if arrival[i] in range(time, time + intervel):
                    qlst.append(i)
                    i += 1
                else:
                    break
            
            wait = 0
            if run[runi] == 0:
                wait = time + intervel - wait0[runi]
            else:
                qlst.append(runi)

            return self.helper(arrival, run, q, cumu+wait, result, time+intervel, qlst, wait0)
        else:
            result.append(cumu)
        

In [284]:
arrival = [0, 1, 4]
run = [5, 2, 3]
q = 3
Solution().waitingTimeRobin(arrival, run, q)

2.3333333333333335

In [285]:
arrival = [0, 1, 4]
run = [2, 5, 3]
q = 3
Solution().waitingTimeRobin(arrival, run, q)

1.6666666666666667

In [286]:
arrival = [1, 3, 4]
run = [5, 5, 3]
q = 3
Solution().waitingTimeRobin(arrival, run, q)

4.666666666666667

In [ ]:
arrival = [0, 1, 4]
run = [5, 2, 3]
q = 3

avg wait time = ((7-0-5) + (5-1-2) + (10-4-3))/3 = (2+2+3)/3 = 2.33 

0~3        3~5              5~7                 7~10
[0, 1]     [0, 1, 4]        [0, 1, 4]           [0, 1, 4]
[5-3, 2]   [5-3, 2-2, 3]    [5-3-2, 2-2, 3]     [-, -, 3-3]
[]         [, 5, ]          [7, 5]              [7, 5, 10]

In [ ]:
arrival = [1, 3, 4]
run = [5, 5, 3]
q = 3

wait0 = [6, 8, 7]

1~4       4~7            7~9          9~12         12~14
[1, 3]    [1, 3, 4]      [1, 3, 4]    [1, 3, 4]    [1, 3, 4]
[5-3, 5]  [5-3, 5-3, 3]  [-, 5-3, 3]  [-, 5-3, -]  [-, -, -]
[]        []             [9, , ]      [9, , 12]    [9, 14, 12]

avg = (3+6+5)/3 = 4.67

In [ ]:
arrival = [0, 1, 4]
run = [2, 5, 3]
q = 3

avg = ((2-0-2) + (8-4-3) + (10-1-5))/3 = (0+1+4)/3 = 1.67

0~2       2~5          5~8            8~10
[0, 1]    [0, 1, 4]    [0, 1, 4]      [0, 1, 4]
[2-2, 5]  [-, 5-3, 3]  [-, 5-3, 3-3]  [-, 5-3-2, -]
[2, , ]   [2, , ]      [2, , 8]       [2, 10, 8]

In [236]:
arrival = [0, 1, 4]
run = [2, 5, 3]


[2, 6, 7]

## Close Two Sum

Given a float capacity, in an array of floats, pick two so that their sum is the closest to and <= target capacity

In [320]:
class Solution:
    def findOptimalWeights(self, capacity, weights, numContainers):
        
        weights.sort()
        l, r = 0, len(weights)-1
        msum = 0
        while l < r:
            s = weights[l] + weights[r]
            if s > msum and s <= capacity:
                msum = s
                first, second = l, r
                l += 1
            elif s > capacity:
                r -= 1
            else:
                l += 1
        return weights[first], weights[second]

In [323]:
import random; random.seed(13)

capacity = 67
weights = random.sample(range(10,40), 10)
print(sorted(weights))
numContainers = 2
print(Solution().findOptimalWeights(capacity, weights, numContainers))

[14, 15, 17, 18, 19, 30, 31, 35, 36, 37]
(30, 37)


## Rotate mxn Matrix

leetcode rotate image

把一个m*n的矩阵旋转90度，给一个flag规定是向左转还是向右转

In [309]:
import numpy as np

class Solution:
    def rotate(self, matrix, flag):
        """
        :type matrix: List[List[int]]
        :rtype: void Do not return anything, modify matrix in-place instead.
        """
        if not matrix.tolist():
            return
        
        # check monotony
        check = []
        [check.extend(row) for row in matrix]
        if check[1:] == check[:-1]:
            return
        
        marr = np.array(matrix)
        # transpose
        marrt = np.transpose(marr)
        # flip
        if flag == 1: # right rotate
            return np.flip(marrt, 1)
        else: # left rotate
            return np.flip(marrt, 0)

In [317]:
matrix = np.arange(10).reshape((5,2))
print(matrix)
flag = 1 # right
print(Solution().rotate(matrix, flag))
flag = 0 # left
print(Solution().rotate(matrix, flag))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[8 6 4 2 0]
 [9 7 5 3 1]]
[[1 3 5 7 9]
 [0 2 4 6 8]]


## Search in 2D Matrix

## Window Minimum

ArrayList = [4, 2, 12, 11, -5]

WindowSize = 2

return ArrayList = [2, 2, 11, -5

## Sorted Insert into Cyclic Linked List

插入一个新的节点到一个sorted cycle linkedlist，返回新的节点。给的list节点不一定是最小节点, 所以先要找到最小的点

In [ ]:
class Node:
    def __init__(self, val, next=None):
        self.value = val
        self.next = next
        
class Solution:
    def insert(self, head, insertVal):
        """
        :type head: Node
        :type insertVal: int
        :rtype: Node
        """
        def insertAfter(node, val):
            node.next = Node(val, node.next)

        if not head: # first node
            node = Node(insertVal, None)
            node.next = node # cyclic linked list
            return node
        
        h = head
        while True:
            if h.val < h.next.val:
                if h.val <= insertVal and insertVal <= h.next.val:
                    h.next = Node(insertVal, h.next)
                    break
            elif h.next.val < h.val:
                if h.val <= insertVal or insertVal <= h.next.val:
                    h.next = Node(insertVal, h.next)
                    break
            else:
                if h.next = head:
                    h.next = Node(insertVal, h.next)
                    break
            h = h.next
        return head

In [ ]:
class Node:
    def __init__(self, val):
        self.value = val
        self.next = None

class LinkedList:
    # initialize root
    def __init__(self):
        self.root = None
        self.size = 0
    
    # insert a new node at the beginning
    def push(self, value):
        new_node = Node(value)
        new_node.next = self.root
        self.root = new_node
        self.size += 1
    
    # print the linked list
    def printlst(self):
        tmp = self.root
        print(tmp.value)
        tmp = tmp.next
        while tmp:
            print(tmp.value)
            tmp = tmp.next
    
    def sortedInsert(self, value)
    
            

## right rotation

Given a string s1 and a string s2, write a snippet to say whether s2 is a rotation of s1?

**example:**

given s1 = ABCD and s2 = CDAB, return true

given s1 = ABCD, and s2 = ACBD , return false)

In [17]:
class Solution:
    def rightRotation(self, word1, word2):
        if not word1 or not word2 or len(word1) < 0 or len(word2) < 0 or len(word1) != len(word2):
            return -1
        tmp = word1 + word1
        if word2 in tmp:
            return 1
        else:
            return -1

print(Solution().rightRotation('ABCD', 'CDAB'))

1


## grey code

Determine if two number are neighbors in grey code sequence

In [152]:
element1, element2 = '0b1000100', '0b1000110'
int(element1, 2) ^ int(element2, 2)

2

## remove vowel

## Close Two Sum

findOptimalWeights

現在給某個容量(double capacity), 還有一個array(double[] weights), 和int numOfContainers

主要是要在array中選出兩個weights總和小於等於capacity但最接近capacity 然後指定到一個Container object並且return first和second的順序並不影響，numOfContainer在java裡好像也是沒有用的,因為double[]本身就自帶length資訊

最後用了最簡單的方法兩個 for loop找總和最接近capacity的pair

總共8個test cases直接就過了

In [209]:
def findOptimalWeights(capacity, weights, numOfContainers=2):
    if not weights:
        return
    if len(weights) < numOfContainers:
        return weights
    
    weights.sort()
    i, j = 0, len(weights)-1
    res, ti, tj = 0, i, j
    while i < j:
        s = weights[i] + weights[j]
        if s > res and s <= capacity:
            res = s
            ti, tj = i, j
            i += 1
        elif s > capacity:
            j -= 1
        else:
            i += 1
    return [weights[ti], weights[tj]]

In [217]:
import random; random.seed(123)
arr = random.sample(range(10,60),10)
print(arr)

[13, 27, 15, 36, 58, 16, 12, 34, 44, 45]


In [218]:
findOptimalWeights(83, arr)

[36, 45]

In [219]:
arr.sort()
print(arr)

[12, 13, 15, 16, 27, 34, 36, 44, 45, 58]


In [155]:
# O(n+n^2)
class Solution:
    def threeSumClosest(self, nums, target):
        """
        :type nums: List[int]
        :type target: int
        :rtype: int
        """
        # base case
        if not nums or len(nums) < 3:
            return
        
        result = nums[0] + nums[1] + nums[2]
        for i in range(len(nums)-2):
            l, r = i+1, len(nums)-1
            while l < r:
                s = nums[i] + nums[l] + nums[r]
                if s == target:
                    return s
                if abs(s-target) < abs(result-target):
                    result = s
                if s < target:
                    l += 1
                elif s > target:
                    r -= 1
        return result
        
if __name__ == '__main__':
    arr = [-1, 2, 1, -4]
    arr = [0,0,0]
    arr = [1,2,4,8,16,32,64,128]
    arr = [-3,-2,-5,3,-4]
    t = -1
    print(Solution().threeSumClosest(arr, t))

-3


In [61]:
n = 3
for i in range(2**3):
    print(2**n+i/2^i)

8.0
8.5
8.5
8.375
8.25
8.15625
8.09375
8.0546875
